### PR TITLE
Further social links

### PR DESCRIPTION
**Pull request by bkmgit**
@Fnyasimi @karegapauline Partially addressing https://github.com/bioinformatics-hub-ke/BOSS22/issues/25 though updates may be needed

### CODE REVIEW

**Review by Fnyasimi — COMMENTED** [review]
Will these align to the right or bottom?

**Comment by bkmgit** [comment]
Yes, on right and at bottom
IconLocation
.

**Comment by Fnyasimi** [comment]
I was thinking of having them listed on the right hand side for good visibility. The logos seem to take much of the attention so having them listed to the right will make them outright visible and also cover the blank space there. I don't know how easy it is to implement this though.

**Comment by bkmgit** [comment]
Ce
CenteredText
ntered seems nicer and have updated the pull request for this. However can also use left or right
LeftText
403-c799-4f44-96d4-11d640eaac69.png)
.

**Comment by Fnyasimi** [comment]
I think the centering leaves more space in between the sponsors; how about you move the social media to the left like below?
Screen Shot 2022-03-11 at 8 23 40 AM

**Comment by bkmgit** [comment]
Thanks for the suggestion. Updated
Footer
.

**Review by Fnyasimi — APPROVED** [review]

**Pull request merged**
