### PR TITLE
Add latest banner

### PR DESCRIPTION
**Pull request by Fnyasimi**
This is the new banner  for #49 and #1

### CODE REVIEW

**Comment by bkmgit** [comment]
The file has some linked images. If these are SVG they should be in the file.  If not, it is possible to add a simple double helix, for example as shown in the images at https://github.com/bioinformatics-hub-ke/BOSS22/pull/49 - line thickness can be increased, colors can alternate between pink #F34A53 and teal #1E4147 or pink #F34A53 and cream #FAE3B4 

The text in white should have a background color so it can also be used in the light theme, perhaps gray #808080, black or pink #F34A53 can be used.

**Comment by bkmgit** [comment]
Can merge and make some of these changes. Maybe can use [Yellowtail font](https://www.fontsquirrel.com/fonts/list/find_fonts?filter%5Bclassifications%5D%5B0%5D=handdrawn&filter%5Bclassifications%5D%5B1%5D=handdrawn&filter%5Blicense%5D%5B0%5D=open) for the top text - it has a permissive license.

**Review by bkmgit — COMMENTED** [review]
Thanks for this.

**Comment by kipkurui** [comment]
@bkmgit it still works fine work without the Text.

**Comment by bkmgit** [comment]
Possible modified version
banner2paths

**Comment by bkmgit** [comment]
Cursive font is [Yellowtail](https://www.fontsquirrel.com/fonts/yellowtail?filter%5Blicense%5D%5B0%5D=open&filter%5Btags%5D%5B0%5D=elegant), regular font is [Alegreya](https://www.fontsquirrel.com/fonts/alegreya?filter%5Blicense%5D%5B0%5D=open&filter%5Btags%5D%5B0%5D=elegant)

**Comment by bkmgit** [comment]
It is helpful to convert fonts to paths since the fonts may not be installed on the users computer.

**Comment by bkmgit** [comment]
@Fnyasimi Made a pull request to your fork with svg files for the above. Feel free to modify if appropriate.

**Comment by Fnyasimi** [comment]
@bkmgit this has a mix up colour on the logo. Lets use what Mike did its okay without the text

**Comment by bkmgit** [comment]
jpg does not scale well on different screen sizes - one would usually have several different resolutions, then serve the appropriate one based on device being used.

Image below shows missing linked figures

banner bhk new

Do also ensure that any figures used that are not original are appropriately licensed/credited.
.

**Comment by bkmgit** [comment]
@Fnyasimi @LandiMi2 Feel free to change the colors. However, the banner should work on both light and dark backgrounds.  Images from your own research would also be great. As an example have downloaded [6ljb](https://www.rcsb.org/structure/6LJB) and created a png file using [jmol](http://jmol.sourceforge.net/) that could be traced to produce an svg file. A list of visualization software for PDB files is available at https://www.rcsb.org/docs/additional-resources/molecular-graphics-software Another such tool is [VESTA](http://jp-minerals.org/vesta/en/
6ljb
)

**Comment by bkmgit** [comment]
Another possible source for an image https://www.researchsquare.com/article/rs-78868/v1

**Comment by bkmgit** [comment]
Image of [1pbr](https://www.rcsb.org/structure/1pbr) part of 16S made using [ParaView](https://www.paraview.org/), which can export a small SVG.

**Comment by bkmgit** [comment]
Image of [1bna](https://github.com/pu-bioinformatics/PythonMiniProject-Fnyasimi/blob/master/Data/1bna.pdb) obtained from [VESTA](http://www.jp-minerals.org/vesta/en/features.html) with output traced using [Inkscape](https://inkscape.org/
1bna png
)

**Comment by Fnyasimi** [comment]
looks better you can give it the green colour theme

**Comment by bkmgit** [comment]
@Fnyasimi Let me know if ok. It is 1Mb which is quite big though. Perhaps have a smaller selection of atoms only on the left?
banner3

**Comment by bkmgit** [comment]
@Fnyasimi @kipkurui Updated banner also in https://github.com/Fnyasimi/BOSS22/pull/1
banner4

**Comment by Fnyasimi** [comment]
use our theme colour #404096 code instead of grey. Also you might want to fix bhki logo

**Comment by bkmgit** [comment]
Updating to use https://www.rcsb.org/structure/2MK1 from which VESTA can produce an SVG image with a small size
2MK1_compressed

**Comment by bkmgit** [comment]
Contrast of 404096 with black is not very good, so have switched it with green.
banner4

**Comment by Fnyasimi** [comment]
@bkmgit  this is good put it up on a diff PR

**Comment by bkmgit** [comment]
merging this so can update the file.

**Pull request merged**
