### PR TITLE
Add the Zoom Events Registration link

### PR DESCRIPTION
**Pull request by kipkurui**

### CODE REVIEW

**Comment by kipkurui** [comment]
@LandiMi2 check this and merge is it is fine.

**Comment by bkmgit** [comment]
Would prefer to improve registration.bhki.org but no strong objection as I do not maintain bhki records.

**Comment by kipkurui** [comment]
> 

That would be ideal, but I feel that we have a very long registration process. Even if they register on registration.bhki.org, they will have to register again on Zoom Events. We need to ease the process, make it easy to track things. We can export the registration details from Zoom Events and add them to the database.

**Review by LandiMi2 — APPROVED** [review]
link works fine

**Comment by bkmgit** [comment]
Cannot merge this since think that developing programming, data management and testing capacity on registration.bhki.org is better but will not object to others merging.

**Pull request merged**
