### PR TITLE
Banner

### PR DESCRIPTION
**Pull request by bkmgit**
Partially addressing https://github.com/bioinformatics-hub-ke/BOSS22/issues/1

### CODE REVIEW

**Comment by bkmgit** [comment]
@Fnyasimi Please review

**Comment by Fnyasimi** [comment]
@bkmgit  are we using the banner @LandiMi2  did?

**Comment by bkmgit** [comment]
@Fnyasimi @LandiMi2 Maybe merge this for now if location seems ok since we still want to use an SVG file for the banner. One can then update colors in either/both webpage and new banner.

**Comment by Fnyasimi** [comment]
@bkmgit I don't think Mike has  lots of time but we can use the banner he created on the page. I think its cool following the discussion on slack

**Comment by bkmgit** [comment]
@LandiMi2 @Fnyasimi Would be great if banner could be uploaded here.

**Comment by bkmgit** [comment]
UpdatedScreenshot

**Comment by bkmgit** [comment]
Done.
Screenshot

**Review by Fnyasimi — APPROVED** [review]
looks good

**Pull request merged**
