### PR TITLE
Update committee.markdown

### PR DESCRIPTION
**Pull request by nanjalaruth**

### CODE REVIEW

**Comment by bkmgit** [comment]
Thanks. Can you add a picture or avatar to https://github.com/nanjalaruth/BOSS22/tree/patch-1/assets/images ?

**Comment by bkmgit** [comment]
If possible a Kiswahili translation in https://github.com/nanjalaruth/BOSS22/blob/patch-1/pages/sw/committee.markdown would be nice as well.

**Comment by nanjalaruth** [comment]
Hi Benson,

I am unable to add the picture as I do not have push rights.

It would be great if you could add it for me. See attached.

Regards,
Ruth.

**Comment by nanjalaruth** [comment]
Greetings,

Currently working on the Swahili translation.

Regards,
Ruth.

**Comment by bkmgit** [comment]
> Hi Benson, I am unable to add the picture as I do not have push rights. It would be great if you could add it for me. See attached. Regards, Ruth.
> […](#)
Add the picture to your fork of the repository where you should have push rights. It can then be merged.

**Review by Fnyasimi — APPROVED** [review]

**Comment by nanjalaruth** [comment]
Hi Benson,

I am unable to add the picture as I do not have push rights.

It would be great if you could add it for me. See attached.

Regards,
Ruth.

**Comment by bkmgit** [comment]
@nanjalaruth This was added. https://bosscon2022.bhki.org/sw/committee/#ruth-nanjala

**Pull request merged**
